---
- name: Include a playbook from a collection
  ansible.builtin.import_playbook: alnpir.main.dummy

- name: Include a role from a collection
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: alnpir.main.dummy
