FROM docker.io/nginxinc/nginx-unprivileged:1.25.4

HEALTHCHECK --interval=30s --timeout=3s \
    CMD curl -f http://localhost/ || exit 1

COPY ./index.html /usr/share/nginx/html/index.html

USER nginx
