- name: Simple ping
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:

    - name: Gather facts for first time
      ansible.builtin.setup:

    - name: Example from an Ansible Playbook
      ansible.builtin.ping:
