- name: Create infrastructure
  ansible.builtin.import_playbook: infrastructure.yml

- name: Configure instances
  ansible.builtin.import_playbook: configure_instances.yml

- name: Run atomic red team tests
  ansible.builtin.import_playbook: atomic_red_team.yml
